service: paramiko-py39

provider:
  name: aws
  profile: jb
  region: ${opt:region, 'eu-east-1'}

layers:
  paramiko:
    path: build
    name: paramiko-py39
    description: Provides Paramiko SSH library for Python
    compatibleRuntimes:
      - python3.9
    allowedAccounts:
      - '*'
    retain: true
